apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxt-frontend
  namespace: elsewedy-app
  annotations:
    reloader.stakater.com/auto: "true"
    reloader.stakater.com/configmap: "ecatalog-config,ecatalog-appsettings,ecatalog-env"
    reloader.stakater.com/secret: "ecatalog-secret"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nuxt-frontend
  template:
    metadata:
      labels:
        app: nuxt-frontend
    spec:
      containers:
        - name: nuxt-frontend
          image: europe-west1-docker.pkg.dev/poc-elsewedy-0825/elsewedy-repo-elsewedy/frontend:1eec07e
          ports:
            - containerPort: 3228
          envFrom:
            - configMapRef:
                name: ecatalog-config
            - secretRef:
                name: ecatalog-secret
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
          - name: env-file
            mountPath: /app/server/.env
            subPath: .env
      volumes:
      - name: env-file
        configMap:
          name: ecatalog-env
